name: "Checks"
on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build-check:
    name: 🗿 Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Build
        run: nix develop -c make production
